### ISSUE TITLE
I have multiple MP1s. How can I set it up?

### ISSUE THREAD

**Issue by jveay** [af950833/Home-Assistant-Broadlink-MP1-Custom-Component#1]
Hello, thank you very much for providing this component. I want to ask. If I have multiple MP1s. How can I set it up?

**Comment by af950833** [comment]
Sorry for late reply.
I am using 4 MP1s with this components.
You need add another 4 switches of MP1 with its IP and MAC.
Refer to the below.

Switch:
#Broadlink Livingroom MP1
  - platform: broadlink_mp1
    host: 192.168.0.9
    mac: 'AA:AA:AA:AA:AA:AA'
    type: mp11
    friendly_name: 'Livingroom MP1 SW 1'

  - platform: broadlink_mp1
    host: 192.168.0.9
    mac: 'AA:AA:AA:AA:AA:AA'
    type: mp12
    friendly_name: 'Livingroom MP1 SW 2'
    
  - platform: broadlink_mp1
    host: 192.168.0.9
    mac: 'AA:AA:AA:AA:AA:AA'
    type: mp13
    friendly_name: 'Livingroom MP1 SW 3'
    
  - platform: broadlink_mp1
    host: 192.168.0.9
    mac: 'AA:AA:AA:AA:AA:AA'
    type: mp14
    friendly_name: 'Livingroom MP1 SW 4'

#Broadlink Desk JS MP1    
  - platform: broadlink_mp1
    host: 192.168.0.10
    mac: 'BB:BB:BB:BB:BB:BB'
    type: mp11
    friendly_name: 'Desk JS MP1 SW 1'

  - platform: broadlink_mp1
    host: 192.168.0.10
    mac: 'BB:BB:BB:BB:BB:BB'
    type: mp12
    friendly_name: 'Desk JS MP1 SW 2'
    
  - platform: broadlink_mp1
    host: 192.168.0.10
    mac: 'BB:BB:BB:BB:BB:BB'
    type: mp13
    friendly_name: 'Desk JS MP1 SW 3'
    
  - platform: broadlink_mp1
    host: 192.168.0.10
    mac: 'BB:BB:BB:BB:BB:BB'
    type: mp14
    friendly_name: 'Desk JS MP1 SW 4'

**Comment by jveay** [comment]
Great,it's working.Thanks
