### ISSUE TITLE
Does not update the state.

### ISSUE THREAD

**Issue by kazihaha** [af950833/Home-Assistant-Broadlink-MP1-Custom-Component#3]
It does not update the state of MP1. Please take a look

**Comment by af950833** [comment]
Hi,

In my HA, it works well in latest version 0.101.0
You have to provide your HA version and type(Hass.io or Hassbian etc..).
Also we need the error log.

**Comment by af950833** [comment]
I ammeded the below in the manifest.json
Please replace it and try again.
"requirements": ["broadlink==0.12.0"],

**Comment by kazihaha** [comment]
> 
> 
> Hi,
> 
> In my HA, it works well in latest version 0.101.0
> You have to provide your HA version and type(Hass.io or Hassbian etc..).
> Also we need the error log.

I'm using 0.103 and in ubuntu, hassio.
When I toggle it on, than I use e-control to turn off one of theme, hassio does not update the state

**Comment by kazihaha** [comment]
> 
> 
> I ammeded the below in the manifest.json
> Please replace it and try again.
> "requirements": ["broadlink==0.12.0"],

Hi, it worked :D Thanks for your helping me :D
