### ISSUE TITLE
Not working on 2021.4.6

### ISSUE THREAD

**Issue by seederp2p** [af950833/Home-Assistant-Broadlink-MP1-Custom-Component#7]
Hi!

I've been using this custom component for a while but after upgrade to 2021.4.6 it doesn't work.

Last working version: 2021.3.4

Any help?

**Comment by nirkons** [comment]
> Hi!
> 
> I've been using this custom component for a while but after upgrade to 2021.4.6 it doesn't work.
> 
> Last working version: 2021.3.4
> 
> Any help?

I've moved to the official broadlink integration, 
I used the custom one since MP1 was broken at some point but it seems it was also fixed at some point, now MP1 is working great with the official hass integration

**Comment by seederp2p** [comment]
ok thanks!
